name: Expo Doctor (expo)

on:
  push:
    branches:
      - main
      - master
    paths:
      - "package.json"
      - "package-lock.json"
  pull_request:
    paths:
      - "package.json"
      - "package-lock.json"

jobs:
  doctor:
    name: Expo Doctor (expo)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: 🚑 Run Doctor Checks
        run: npx expo-doctor@latest
