name: Expo Doctor (expo)

on:
  push:
    branches:
      - main
      - master
    paths:
      - "package.json"
      - "package-lock.json"
  pull_request:
    paths:
      - "package.json"
      - "package-lock.json"

jobs:
  doctor:
    name: Expo Doctor (expo)
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + install deps
        uses: ./.github/actions/setup-node-install

      - name: 🚑 Run Doctor Checks
        run: npx expo-doctor@latest
