name: Prettier Check and Auto-Fix

on:
  push:
    branches:
      - main
      - master
    paths:
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.json"
      - "**/*.md"
  pull_request:
    paths:
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.json"
      - "**/*.md"

jobs:
  prettier:
    name: Run Prettier and Commit Changes
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: 🔧 Install dependencies
        run: npm ci

      - name: 🔧 Run Prettier (Auto-fix)
        run: npm run prettier -- --write .

      - name: 🔧 Commit and push Prettier fixes
        run: |
          # Check if Prettier made any changes
          git diff --exit-code || (
            echo "Changes detected by Prettier, committing and pushing changes" &&
            git config --global user.name "GitHub Actions" &&
            git config --global user.email "actions@github.com" &&
            git add . &&
            git commit -m "fix: apply Prettier formatting" &&
            git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/wsorto89/rn-expo-products.git HEAD:${{ github.head_ref }}
          )
